sudo: required
services:
  - docker

# https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
before_install:
  - docker build -t mapundir7/program-1 -f program-1/Dockerfile.dev .

script:
  - docker run mapundir7/program-1

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-west-2-306476627547"
#   bucket_path: "docker"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"

